kind: Service
apiVersion: v1
metadata:
  name: error-log-clustering
  namespace: operational-intelligence
  labels:
    k8s-app: error-log-clustering
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    k8s-app: error-log-clustering
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: error-log-clustering
  namespace: operational-intelligence
  labels:
    k8s-app: error-log-clustering
  annotations:
    kubernetes.io/ingress.class: nginx    
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - elc.uc.ssl-hep.org
    secretName: elc-cert
  rules:
    - host: elc.uc.ssl-hep.org
      http:
        paths:
        - path: /
          backend:
            serviceName: error-log-clustering
            servicePort: 80